package id.infinitelearning.KotlinSubmission.exercise4

fun main() {

    try {
        var x = 100
        var y = 0
        var pembagian = x / y
    } catch (e: ArithmeticException) {
        println("Pembagian terhadap angka 0 tidak dapat dilakukan")
    }
}
    /**
     * Buatlah contoh code penggunaan try catch untuk menangani suatu kasus sesuai keinginan teman-teman
     *
     */
    // Buat di bawah sini
